### ISSUE TITLE
web not works!!!

### ISSUE THREAD

**Issue by kenpokas** [s0kil/Spotify-Player#1]
hello my friend!!!tell me please is the correct web?

**Comment by s0kil** [comment]
@kenpokas What is the problem?

**Comment by kenpokas** [comment]
hello!!!my friend says just that...Hello From Svelte! there is nothing else on the web!!!

**Comment by s0kil** [comment]
@kenpokas If you click on the `Svelte` 17 times and 20 times on `Hello` it will unlock the player.

**Comment by kenpokas** [comment]
NOTHING HAPPEN DUDE!!!

Στις Τρί, 24 Δεκ 2019 στις 1:31 π.μ., ο/η Daniel Sokil <
notifications@github.com> έγραψε:

**Comment by s0kil** [comment]
@kenpokas I was joking, We are starting to work on the project soon.

**Comment by kenpokas** [comment]
jajajajajajaaj lollllllllll....but I was try !!!!!My friend tell me please you make it appear albums and songs?

**Comment by s0kil** [comment]
@kenpokas I will let you know once we finish.

**Comment by kenpokas** [comment]
ok my friend!!!thanks so much!!!
