### ISSUE TITLE
I CANT SEARCH NOTHING!!!

### ISSUE THREAD

**Issue by kenpokas** [s0kil/Spotify-Player#5]
MY FRIENDDDDDD AMAZING WEB BUT I CANT SEE MY PLAYLISTS AND I CANT SEARCH!!!ONLY I CAN LOGIN...HELP ME PLEASEEEEEEE DUDE!!!

**Comment by s0kil** [comment]
@kenpokas It takes time to build the web app, we are not robots (:

**Comment by kenpokas** [comment]
aaaaaaaa really I am sorry!!!I thought that was ready!!!ok Man take your time....my friend tell me please something...what you think if you make it appear just the full albums ?it would be greattttttttt...but its up to you!!!!!!!!!!!!!!!

**Comment by s0kil** [comment]
> make it appear just the full albums

@kenpokas What do you mean?

**Comment by s0kil** [comment]
@kenpokas https://github.com/s0kil/Spotify-Player#status
